---
title: "ETC5521 Assignment 1"
subtitle: "Tour de france"
team: Grevillea
author:
  - Samuel Lyubic
  - Brendi Ang
date: "`r Sys.Date()`"
output: 
  html_document
---

[This assignment is for ETC5521 Assignment 1 by Team `r rmarkdown::metadata$team` comprising of `r knitr::combine_words(rmarkdown::metadata$author)`.]{style="color:#006DAE;"}


# Introduction and motivation

[FILL] Give the bigger picture of the data, and inspire the reader to learn more about the problem by reading your analysis. 

# Data description

The Tour de France (TDF) data shows the results of every race since inception and is being accessed from Alastair Rushworth's Data package _Ttdf_ which is hosted on github. The _tdf_ package acts as a container for the _editions_ tibble, which sourced it's data from Wikipedia and offers a tibble that presents observations ranging from the first Tour de France in `r min(editions$start_date)` through to the most recent in `r max(editions$start_date)`, with 109 rows corresponding to each edition of the Tour and 20 columns containing the variables of each race. The key variables include:
  - _edition_: The edition of the Tour de France.
  - _start_date_: The date the Tour started.
  - _winner_name: Name of the winner.
  - _winner_team: Name of the winning team.
  - _distance_: The total distance of the race in kms's.
  - _time_overall_: The total time it took the winner to compelete the route, in hours.
  - _time_margin_: The time difference between first place and second place, in hours.
  - _stage_wins_: The number of stages the overall winner won.
  - _stages_led_: The number of stages the overall winner spent as the leader of the race. 
  - _height_: Height of the winner, in meters.
  - _age_: Age of the winner.
  - _weight_: Weight of the winner, in kg's.
  - _nationality_: Nationality of winning rider.
  - _stage_results_: Nested details of the results of every stage, including rider and stage information. Missing values were identified for the unnested stage data however, the data has been sourced from wikipedia by using webscraping methods. 

For this report the _editions_ tibble has been broken down into two seperate datasets:
  1. Overall TDF winners in _winners_ which has 106 observations and 19 variables
  2. TDF Stage winners in _stage_clean_ which has 255,752 observations and 11 variables 

**Primary Question:**  
What are the most important characteristics and attributes to win the tour and how have they evolved over time?

**Secondary:**  
1. What is the average speed of overall winners for each stage? 
  - Are they faster in a certain terrain (e.g. hill, mountain, flat)? 
  - How important are stage wins for the overall winner? - Note: complements Q3.
  - Are there certain tracks/terrains that most riders fail to complete (i.e. NA in rank/elpased in stage data)?

2. Is there a change in biological/physical traits of overall winners over the years? 
  - Do overall winners, top sprinters or climbers have similar features (e.g. body type, age)?      Were they consistent over the years?
  - Are competitors younger/older these days?
  - Is a certain team producing winners more prevalently? - e.g. Do these teams have good salary, nutritionists etc.
  - Is a certain nation producing winners more prevalently?

3. How many stages does an overall winner usually lead by? Do they usually wear the yellow jersey from start to end?
  - Is there a specific trend (e.g. Win in the last few stages or do they win certain terrains like mountain stages)?          
    - *Note:* don't have to win any stages or have the most points to be overall winner
  - How are they ranked in each stage?
# Analysis and findings

[FILL] Should include at least one plot or numerical summary for each of your questions, that helps the reader arrive at an answer. You should also write paragraphs describing the methods, summaries and findings. 

# References

